services:
  postgres:
    image: postgres:15-alpine
    container_name: user_management_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_management_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/user_management?schema=public"
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
      JWT_EXPIRES_IN: "24h"
      PORT: 3000
      NODE_ENV: "production"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
